package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.34

import (
	"context"

	"cinematic.back/api/users/pb"
	"cinematic.back/services/gateway/internal/api/graphql/model"
)

// AuthByCredentials is the resolver for the authByCredentials field.
func (r *mutationResolver) AuthByCredentials(ctx context.Context, input model.AuthByCredentialsInput) (*model.AuthByCredentialsResponse, error) {
	req := &pb.AuthByCredentialsRequest{Credentials: &pb.UserCredentials{
		Email:    input.Email,
		Password: input.Password,
	}}
	res, err := r.uClient.AuthByCredentials(ctx, req)
	if err != nil {
		return nil, err
	}

	resp := &model.AuthByCredentialsResponse{
		AccessToken:  res.AccessToken,
		RefreshToken: res.RefreshToken,
	}

	return resp, err
}

// Register is the resolver for the register field.
func (r *mutationResolver) Register(ctx context.Context, input model.RegisterRequestInput) (*model.RegisterResponse, error) {
	req := &pb.RegisterRequest{
		Credentials: &pb.UserCredentials{
			Email:    input.Email,
			Password: input.Password,
		},
		Username: input.Username,
	}
	res, err := r.uClient.Register(ctx, req)
	if err != nil {
		return nil, err
	}

	resp := &model.RegisterResponse{
		AccessToken:  res.AccessToken,
		RefreshToken: res.RefreshToken,
	}

	return resp, nil
}

// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context, refreshToken string) (*model.RefreshTokenResponse, error) {
	req := &pb.RefreshTokenRequest{RefreshToken: refreshToken}
	res, err := r.uClient.RefreshToken(ctx, req)
	if err != nil {
		return nil, err
	}

	resp := &model.RefreshTokenResponse{
		AccessToken:  res.AccessToken,
		RefreshToken: res.RefreshToken,
	}

	return resp, err
}
